baseURL = "https://www.shiatsu-zen.co"
defaultContentLanguage = "en"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT", "404"]
theme = "hugo-product-launch"
title = "Shiatsu Zen Co."
[markup.goldmark.renderer]
hardWraps = true
[params]
copyright = "© Shiatsu Zen Co."
description = "You don't even know what we can do for you!"
favicon = "images/favicon.png"
hidedesignbyline = true
images = ["/conscious-design-qxdjhlp59-o-unsplash.jpg"]
title = "Shiatsu Zen Co."
[params.meta]
keywords = "shiatsu, zen, massage"
